export const CONFIG = Object.freeze({
  protocolVersion: 1 as const,
  universeId: 'local-earth-01',
  shipId: 'kestrel-01',
  earthRadius: 6378137,
  earthMu: 3.986004418e14,
  initialAltitude: 400000,
  epochMs: Date.UTC(2026, 8, 6, 12),
  fixedDt: 1 / 60,
  snapshotHz: 20,
  inputHz: 20,
  inputTimeoutMs: 250,
  standardGravity: 9.80665,
  specificImpulseSeconds: 320,
  dryMassKg: 6000,
  initialPropellantKg: 2000,
  initialModuleMassKg: 0,
  initialCargoMassKg: 0,
  initialAmmunitionMassKg: 0,
  lowFuelPropellantKg: 80,
  lowReserveDeltaVMps: 100,
  startingCredits: 2500,
  cargoMissionMassKg: 320,
  cargoMissionRewardCredits: 1400,
  cargoMissionRewardReputation: 8,
  reconMissionRewardCredits: 1050,
  reconMissionRewardReputation: 6,
  reconScanSeconds: 5,
  interceptRewardCredits: 1250,
  interceptRewardReputation: 7,
  missionOrbitToleranceM: 20_000,
  fuelCreditsPerKg: 0.35,
  ammunitionCreditsPerKg: 2,
  repairCreditsPerPercent: 10,
  combatTagDurationMs: 300_000,
  laserRangeM: 3_000,
  laserArcDegrees: 32,
  laserDamage: 12,
  laserEnergyCost: 18,
  laserHeatPerShot: 24,
  laserCooldownMs: 450,
  laserEnergyRechargePerSecond: 16,
  laserHeatDissipationPerSecond: 13,
  missileMassKg: 8,
  missileDamage: 28,
  missileCooldownMs: 1_500,
  missileLifetimeSeconds: 12,
  missilePropulsionSeconds: 6,
  missileAccelerationMps2: 85,
  missileTurnRateRadPerSecond: 1.35,
  missileLaunchSpeedMps: 160,
  missileFuseRadiusM: 65,
  countermeasureCharges: 4,
  countermeasureCooldownMs: 5_000,
  countermeasureRangeM: 3_000,
  interceptDamageRequired: 100,
  botLaserDamage: 8,
  botLaserCooldownMs: 1_400,
  botMissileCooldownMs: 5_000,
  botInitialMissileAmmunitionKg: 24,
  stationAltitudeM: 450_000,
  stationInitialPhaseRad: 0.025,
  stationBodyRadiusM: 45,
  stationPortCapturePointM: 54,
  stationRendezvousRangeM: 5_000,
  stationRendezvousHandoffOffsetM: 200,
  stationRendezvousRelativeSpeedMps: 75,
  stationFinalApproachRangeM: 250,
  stationFinalApproachRelativeSpeedMps: 10,
  stationCaptureRadiusM: 3.5,
  stationMaxDockingRelativeSpeedMps: 1,
  stationMaxDockingClosingSpeedMps: 0.8,
  stationMaxDockingLateralErrorM: 2.5,
  stationMaxDockingAlignmentErrorDeg: 12,
  stationMaxDockingRollErrorDeg: 15,
  stationHardImpactSpeedMps: 5,
  stationUndockSeparationM: 14,
  stationUndockSpeedMps: 0.5,
  bountyScoutRewardCredits: 1800,
  bountyFighterRewardCredits: 3200,
  bountyHeavyRewardCredits: 4800,
  bountyScoutReputation: 5,
  bountyFighterReputation: 10,
  bountyHeavyReputation: 16,
  bountyInterceptHandoffRangeM: 1_200,
  bountyAcquireRangeM: 5_000,
  raptorInsuranceDeductibleCredits: 600,
  moduleDamageMultiplier: 1.6,
  mainThrustN: 24000,
  translationThrustN: 8000,
  angularRate: 0.35,
  angularAcceleration: 0.65,
  port: 8787,
  maxPayloadBytes: 4096,
  maxCommandsPerSecond: 100,
});
export const SCENES = [
  'orbit_day',
  'orbit_night',
  'orbit_maneuver',
  'low_fuel',
  'cargo_mission',
  'intercept',
  'missile_hit',
  'station_rendezvous',
  'station_docking',
  'bounty_sandbox',
] as const;
export type SceneId = (typeof SCENES)[number];
